### ISSUE TITLE
"restart required" warning because of poll plugin

### ISSUE THREAD

**Issue by crazycells** [NodeBB/nodebb-plugin-poll#105]
https://community.nodebb.org/topic/14174/restart-required-warning-does-not-go-away

**Comment by crazycells** [comment]
additionally, with nodebb 1.12.2 it does not let you create a poll.

**Comment by akhoury** [comment]
@crazycells the restart required issue is fixed, will publish soon. 

What exactly happens on 1.12.2?I just created a test poll 

![Screen Shot 2019-09-03 at 11 26 41 AM](https://user-images.githubusercontent.com/1398375/64156633-d85fe180-ce3d-11e9-86ca-494f51e8ecdf.png)

**Comment by arranka** [comment]
we are not allowed to create a survey in node 1.12.2

![image](https://user-images.githubusercontent.com/30248115/64194705-33053780-ce56-11e9-8b43-670fe0fb5fa7.png)

**Comment by akhoury** [comment]
On your terminal, assuming you have mongo client installed, can you query the `global`
```
mongo
use forobolso;
db.objects.findOne({ _key: "global" })
```
then 
```
db.objects.aggregate([ { $match: { _key: "polls" } }, { $project: { count: { $size: '$array' } } } ])
```

Paste both results here, don't worry, `global` does not have any sensitive information. In fact, I am mostly interested in the `nextPollId` property, and the second command counts how many polls you already have in there. I want to make sure the that the `nextPollId` is greater than the count of the polls. 

Thanks.

**Comment by crazycells** [comment]
@akhoury Thanks a lot, we have resolved the issue. We needed to uninstall and install again, I do not know what the problem was, but now it is working. Thanks.

**Comment by Pummelchen** [comment]
Same issue here "restart required" is shown permanent in the ACP after the poll plugin was install.
The plugin itself works, just the ACP status seems to be confused ..

**Comment by akhoury** [comment]
0.3.3 needs to be published, @julianlam

**Comment by akhoury** [comment]
nodebb-plugin-poll@0.3.3 published
