### ISSUE TITLE
disable option sorting

### ISSUE THREAD

**Issue by awunnenb** [NodeBB/nodebb-plugin-poll#109]
How can we disable option sorting? We don't need an alphabetic order. We need the options in order we typed them in.

**Comment by julianlam** [comment]
Can you let me know how it is using alpha sort? I can't seem to reproduce this issue:

![image](https://user-images.githubusercontent.com/923011/97756412-2f5c5780-1ad1-11eb-82ef-02616b0fc349.png)

**Comment by pitaj** [comment]
Please provide the database you're using, I'd bet that plays a role.

**Comment by awunnenb** [comment]
the alphabetic sorting happens on mongodb.

**Comment by awunnenb** [comment]
<img width="649" alt="Bildschirmfoto 2020-11-02 um 20 31 18" src="https://user-images.githubusercontent.com/2630920/97910842-9c2e5680-1d4a-11eb-81f0-339e5cc37238.png">

installed 1.1.0 but newest is 0.3.7 ??? 

i can't reproduce now too.

**Comment by julianlam** [comment]
@awunnenb Thanks for confirming.

Might be nbbpm has not caught up yet :)

**Comment by awunnenb** [comment]
with 1.1.0 it works fine! ... but we need anonymus voting :-)
