### ISSUE TITLE
Not able to create poll when using Quill composer

### ISSUE THREAD

**Issue by magnusvhendin** [NodeBB/nodebb-plugin-poll#114]
I'm moving from Redactor to Quill at the moment and I'm having issues with the official poll plugin. When clicking the poll icon it opens up just fine, but when I save nothing happens and I get this in the console `Uncaught TypeError: Cannot convert null or undefined to object`.

Redactor has been completely deactivated and removed.

It seems like [this is where it starts](https://github.com/NodeBB/nodebb-plugin-poll/blob/6ea0ed62ecacc9b82bb938015e19394a65268b12/public/js/poll/creator.js#L28). The textarea gets passed into composerBtnHandle and then when Creator.show is called it tries to parse the value from textarea which is empty when using Quill. [This](https://github.com/NodeBB/nodebb-plugin-poll/blob/6ea0ed62ecacc9b82bb938015e19394a65268b12/public/js/poll/creator.js#L98) is where it tries to parse out markdown from an undefined value.

Environment:
NodeBB: 1.14.3
nodebb-theme-persona: 10.1.65
nodebb-plugin-composer-default: 6.3.50
nodebb-plugin-composer-quill: ^1.7.0
nodebb-plugin-poll: ^0.3.7

**Comment by julianlam** [comment]
Thanks  for reporting, I'll take a look at this incompatibility today if I can.

**Comment by julianlam** [comment]
Ah it's a little more complicated than that, it looks like the poll plugin is incompatible with latest NodeBB, so I'll try to fix that up.

**Comment by julianlam** [comment]
Should be resolved with 266d7587b

**Comment by julianlam** [comment]
Closed via #116
