### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by RobertSandiford** [NodeBB/nodebb-plugin-poll#122]
Fresh nodeBB install

Installed plugin through the dashboard, and activated

Post:
Some text

[poll title="abc']
- 1
- 2
[/poll]

Output:
Some text

[poll title="abc']

.1
.2
[/poll]

**Comment by julianlam** [comment]
Hi @RobertSandiford -- have you hit the "Rebuild & Restart" button in the admin dashboard after activating the plugin? (or running `./nodebb build` and restarting nodebb)

**Comment by RobertSandiford** [comment]
I pressed "restart" not "rebuild and restart" because the alert after activation says "Please restart your nodebb to activate this plugin"

Is it possible to change that text?

(Works after rebuild and restart)

**Comment by julianlam** [comment]
@RobertSandiford Thanks for the additional context, that is a good point, and I have updated the text copy accordingly.

**Comment by RobertSandiford** [comment]
> @RobertSandiford Thanks for the additional context, that is a good point, and I have updated the text copy accordingly.

Brillo! : )
