### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by awunnenb** [NodeBB/nodebb-plugin-poll#124]
"defaults": "Standartwerte",
correct: Standardwerte

"default_title": "Standart Titel",
correct: Standard Titel

"error.privilege.create": "You're not allowed to create a poll",
german: "Du bist nicht berechtigt abzustimmen"

i can't find the key for this text to translate in poll.json: "You have already voted and changing your vote is not allowed for this poll"
german: "Du hast bereits abgestimmt und nachträgliche Änderungen sind in dieser Abstimmung nicht erlaubt."

found in en_US: 
"voting_update_disallowed_message": "Du hast bereits abgestimmt und nachträgliche Änderungen sind in dieser Abstimmung nicht erlaubt",

"vote_is_final": "Änderungen sind in dieser Abstimmung nicht erlaubt. Deine Abstimmung ist endgültig!"

**Comment by julianlam** [comment]
v.1.16 -- thanks @awunnenb !
