### ISSUE TITLE
plugin poll doesn't work with last nodebb update (nodebb 2.8.3)

### ISSUE THREAD

**Issue by DroidBV8** [NodeBB/nodebb-plugin-poll#135]
Hello @barisusakli 

I have updated nodebb 2.8.2 to 2.8.3 and this plugin broke nodeBB like the screen above

![image](https://user-images.githubusercontent.com/71468154/214710898-d891debe-e682-424b-b9c4-f4231fc0470a.png)

![image](https://user-images.githubusercontent.com/71468154/214711296-3c624668-92c9-446b-b12f-d03bdd69f1bd.png)

I have test with 

npm install nodebb-plugin-poll
npm install nodebb-plugin-poll@2.0.7
npm install nodebb-plugin-poll@3.0.2

Same result. 

Ok with downgrade nodeBB on 2.8.2

**Comment by barisusakli** [comment]
It looks like your post content is escaped instead being displayed as html, not sure if it's caused by nodebb-plugin-poll to be honest.

When you are on nodebb 2.8.3 does disabling nodebb-plugin-poll display the correct content?

**Comment by DroidBV8** [comment]
Yep @barisusakli 

on nodebb 2.8.3, if I disable nodebb-plugin-poll, the display contant is correct ?

I have test with all my other plugin disabled and enabled nodebb-plugin-poll alone = content display problem

**Comment by barisusakli** [comment]
@DroidBV8 maybe try with nodebb@2.8.4, I have tested a default install with nodebb@2.8.5 and nodebb-plugin-poll@2.0.7 and not seeing what you are seeing.

![image](https://user-images.githubusercontent.com/2583394/214864583-e489ec43-c7db-402b-8e31-3a50fd87e54e.png)
![image](https://user-images.githubusercontent.com/2583394/214864644-cc8da3eb-3f9f-44c9-84c2-416b6f0d02b6.png)


These are the plugins I have active 

```
Active plugins:
        * nodebb-plugin-composer-default@9.2.4 (installed, enabled)
        * nodebb-plugin-emoji@4.0.6 (installed, enabled)
        * nodebb-plugin-emoji-android@3.0.0 (installed, enabled)
        * nodebb-plugin-markdown@10.1.1 (installed, enabled)
        * nodebb-plugin-mentions@3.0.12 (installed, enabled)
        * nodebb-plugin-poll@2.0.7 (installed, enabled)
        * nodebb-rewards-essentials@0.2.1 (installed, enabled)
        * nodebb-theme-lavender@6.0.1 (installed, disabled)
        * nodebb-theme-persona@12.1.12 (installed, enabled)
        * nodebb-widget-essentials@6.0.1 (installed, enabled)
```

**Comment by DroidBV8** [comment]
ok I will test as soon as possible. Last night the last version  was 2.8.3

**Comment by DroidBV8** [comment]
Its' ok with nodebb 2.8.4


Good ;)
