### ISSUE TITLE
Guests cannot view poll box

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/nodebb-plugin-poll#145]
Try to visit a topic with poll as a guest user.
https://community.nodebb.org/topic/17940/do-you-have-limited-or-full-access-to-your-host

Guest and skipped poll box:
![anon](https://github.com/NodeBB/nodebb-plugin-poll/assets/11160550/c2f2e9ae-eb2b-4b11-b257-051c18865836)

Logged-in user able to see poll box and no error:
![anon2](https://github.com/NodeBB/nodebb-plugin-poll/assets/11160550/7e498028-4171-4701-b38f-482d1054a3b1)

**Comment by barisusakli** [comment]
This was an acp setting to allow guests to view posts.

![image](https://github.com/NodeBB/nodebb-plugin-poll/assets/2583394/6b38b842-8840-4330-98fb-a70faa94b11d)
