### ISSUE TITLE
Feature: Anonymous voting

### ISSUE THREAD

**Issue by arasbm** [NodeBB/nodebb-plugin-poll#7]
I noticed in the code there are some references to user but in UI I could not see anything related to users who voted for each category.

Does this plugin support (or plan to support) both anonymous and not anonymous kinds of polls?

By not anonymous I mean for example showing the list of users who voted for each option next to it in the results view.

**Comment by astucieuxzephyr** [comment]
I would really like to have this possibility to vote anonymously  too. :+1:

**Comment by exomarty** [comment]
+1 for this feature

**Comment by jimmykane** [comment]
+1 for me as well

**Comment by soliury** [comment]
+1 for this feature
