### ISSUE TITLE
Unable to create poll due to invalid date? 

### ISSUE THREAD

**Issue by jimmykane** [NodeBB/nodebb-plugin-poll#93]
Hi there, 

some of our users are unable to create a poll due to an invalid date. 

This is their screenshot 

<img width="597" alt="1511820337928-screen-shot-2017-11-27-at-3 03 31-pm" src="https://user-images.githubusercontent.com/1268723/33378373-dc59c658-d514-11e7-976e-9c1738aeb63b.png">

I tried to reproduce this but no luck. 

One thing that can be affecting this is the US locale for dates on the user side

**Comment by jimmykane** [comment]
Also the error message is missing

**Comment by mkunkel** [comment]
We have also had some users experience this error. So far, the issue has only been confirmed on iOS devices.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-plugin-poll/commit/696c6443f94c13d890e983876caacb93c945e8d5
