### ISSUE TITLE
When trying to insert a poll on already written topic gets this error

### ISSUE THREAD

**Issue by FaizanZahid** [NodeBB/nodebb-plugin-poll#96]
E11000 duplicate key error collection: nodebb.objects index: _key_1_value_-1 dup key: { : "poll:99:options", : null }

**Comment by akhoury** [comment]
![Screen Shot 2019-03-12 at 2 57 02 AM](https://user-images.githubusercontent.com/1398375/54168230-35be3b80-4476-11e9-8d30-1d8f69d7410a.png)
