### ISSUE TITLE
Missing permission title

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/nodebb-plugin-poll#99]
I'm using a forum in a German. In the admin CP, the poll permission under user permissions is missing. The whole checkbox-table makes no sense because the poll's permission is skipped.

**Comment by jtsimoes** [comment]
Same here on pt-PT. Text is missing on Group permissions but not on User permissions...

![image](https://user-images.githubusercontent.com/34691647/51433993-1cf09100-1c50-11e9-8c62-ab65f58bc5d7.png)

**Comment by jtsimoes** [comment]
@tom-rade This plugin just got updated! 😮 
And I think this issue got fixed too on https://github.com/NodeBB/nodebb-plugin-poll/commit/fba849e2173a41cf7e29c6ec495fea207804f3b9

**Comment by jtsimoes** [comment]
Yup, **fixed on v0.2.20** :
![image](https://user-images.githubusercontent.com/34691647/52485482-dc31cb00-2bb0-11e9-8690-4e5abb5becb4.png)

You can close this issue @tom-rade 
Thanks @julianlam
